name: Hazelcast
description: |
  Hazelcast is an open source in-memory data grid based on Java.
version: 3.7.1
category: Data Grid
maintainer: Skysoft-ATM
license: # The license
projectURL: # A URL related to the catalog entry