hazelcast-datanodes:
  image: skysoft/hazelcast-conf:1.0.0
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: hazelcast-base-datanode
  volumes_from:
    - hazelcast-base-datanode
hazelcast-base-datanode:
  labels:
    hazelcast.datanode.config.version: '0'  
    io.rancher.container.hostname_override: container_name
  volumes:
    - /opt/hazelcast
  image: hazelcast/hazelcast:3.7.1