elasticsearch-masters:
  image: skysoft/hazelcast-conf:1.0.0
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: hazelcast-node

hazelcast-node:
  labels:
    io.rancher.container.hostname_override: container_name
  image: hazelcast/hazelcast:3.7.1