hazelcast-conf:
  image: skysoft/hazelcast-conf:1.0.0
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: hazelcast-node
  volumes_from:
    - hazelcast-node
hazelcast-node:
  labels:
    hazelcast.datanode.config.version: '0'  
    io.rancher.container.hostname_override: container_name
  volumes:
    - /opt/hazelcast
  image: skysoft/hazelcast-server:3.7.1